// <auto-generated />
using System;
using ClinicaEstetica.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicaEstetica.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527142116_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("ClinicaEstetica.Models.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BiomedicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcedimentoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BiomedicoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProcedimentoId");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("ClinicaEstetica.Models.Biomedico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CRBM")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Biomedicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CRBM = "CRBM-1234",
                            Email = "ana@clinica.com",
                            Especialidade = "Estética Avançada",
                            Nome = "Dra. Ana Paula",
                            Telefone = "11999990001"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CRBM = "CRBM-5678",
                            Email = "carlos@clinica.com",
                            Especialidade = "Harmonização Facial",
                            Nome = "Dr. Carlos Lima",
                            Telefone = "11999990002"
                        });
                });

            modelBuilder.Entity("ClinicaEstetica.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ClinicaEstetica.Models.Procedimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Procedimentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Limpeza profunda com extração",
                            DuracaoMinutos = 60,
                            Nome = "Limpeza de Pele",
                            Preco = 180.00m
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Aplicação de toxina botulínica",
                            DuracaoMinutos = 30,
                            Nome = "Botox",
                            Preco = 800.00m
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Preenchimento com ácido hialurônico",
                            DuracaoMinutos = 45,
                            Nome = "Preenchimento Labial",
                            Preco = 1200.00m
                        });
                });

            modelBuilder.Entity("ClinicaEstetica.Models.Agendamento", b =>
                {
                    b.HasOne("ClinicaEstetica.Models.Biomedico", "Biomedico")
                        .WithMany("Agendamentos")
                        .HasForeignKey("BiomedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaEstetica.Models.Cliente", "Cliente")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaEstetica.Models.Procedimento", "Procedimento")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ProcedimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Biomedico");

                    b.Navigation("Cliente");

                    b.Navigation("Procedimento");
                });

            modelBuilder.Entity("ClinicaEstetica.Models.Biomedico", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("ClinicaEstetica.Models.Cliente", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("ClinicaEstetica.Models.Procedimento", b =>
                {
                    b.Navigation("Agendamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
